### ISSUE TITLE
Data still embargoed

### ISSUE THREAD

**Issue by PeteHaitch** [jaychung10010/Mammary_snATAC-seq#1]
Hi Jay,

With the preprint being available on biorXiv, would you please consider making the data publicly available?
The GEO accession states that 'Accession "GSE125523" is currently private and is scheduled to be released on Sep 01, 2019.'

Cheers,
Pete

**Comment by jaychung10010** [comment]
Sorry for the delay. Raw data was available September last year @ GEO.
