### ISSUE TITLE
Processed peak file(s)

### ISSUE THREAD

**Issue by RegnerM2015** [jaychung10010/Mammary_snATAC-seq#3]
Hi @jaychung10010 ,

Would you be able to share the processed binary peak matrix generated in your tutorial script? Thank you in advance!

```all_distal_bmat <- read.table("fMaSC+adult_v1+2_rep1+2.distal.mat.gz") # this will take a while
all_distal_bmat_sm <- as(as.matrix(all_distal_bmat), "sparseMatrix")
save(all_distal_bmat_sm, file = "./fMaSC+adult_v1+2_rep1+2.distal.sparse_mat.RData")

**Comment by jaychung10010** [comment]
There you go: https://github.com/jaychung10010/Mammary_snATAC-seq/raw/master/fMaSC%2Badult_v1%2B2_rep1%2B2.distal.sparse_mat.RData

**Comment by RegnerM2015** [comment]
Thank you so much @jaychung10010 ! I appreciate your help.

**Comment by jaychung10010** [comment]
No problem!
