### ISSUE TITLE
Data distribution for Monocle pseudotime 

### ISSUE THREAD

**Issue by RegnerM2015** [jaychung10010/Mammary_snATAC-seq#4]
Hi @jaychung10010,

Can you confirm that the chromVAR Monocle pseudo time analysis used the following expression family parameter when setting up the cds object: gaussianff()? 
```
cds <- newCellDataSet(data,phenoData = pd,
                              featureData = fd,
                              lowerDetectionLimit = 0.5,
                              expressionFamily = gaussianff())

**Comment by jaychung10010** [comment]
Hello, I can't tell you for sure as this was a while ago. I used the default distribution from an earlier version of Monocle in 2018. If you are feeding in chromVar z score then I think Gaussian is a good choice.
